# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: floge77/back-end-wvv:latest
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PW }}
          dockerfile: scripts/Dockerfile_with_mvn_build
